resources:
  containers:
  - container: arm32v7-test-container
    image: ghcr.io/electron/build:arm32v7-27db4a3e3512bfd2e47f58cea69922da0835f1d9
    options: --shm-size 128m

jobs:
- job: Test_Arm32v7
  container: arm32v7-test-container
  displayName: Test Arm on Arm32v7 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
